{% extends "base.phtml" %}

	{% block css %}
		<link rel="stylesheet" type="text/css" href="/static/css/home.css">
	{% endblock %}
	
	{% block content %}
	<div ng-controller="dataController">
		<div style="position: absolute; top: 0">
			<h2>HTML</h3> 
		</div>
		
		<div style="position: absolute; top:50%"> 
			<h2>CSS</h3> 
		</div>
		
		
		<div ng-model="message" ng-show="showMessage" class="message fadein fadeout"style="position: absolute; bottom: 14%;">
			<h3>Saved</h3>
		</div>
		
		<button type="button" onclick="getData()" ng-click="save()" style="bottom:9%; !important">
			<img src="http://i.imgur.com/0wFW7Rk.png" style="width: 131px; height: 40px;">
		</button>
		
		<button type="button" onclick="getData()" ng-click="save(1)">
			<img src="http://i.imgur.com/opCfSE2.png" style="width: 131px; height: 40px;">
		</button>		


		<div id="editorHTML">
		 {{html}}
		</div>
		
		
		<div id="editorCSS">
		{{css}}
		</div>

	</div>
	{% endblock %}

	{% block javascript %}
		<script src="/static/js/data.js"></script>
		<script>
			// we declare and initialize our ace.js editor forms.
			
			// this is the initialization of the HTML editor
			// the theme and mode is also initialize
			var editorHTML = ace.edit("editorHTML");
			editorHTML.setTheme("ace/theme/eclipse");
			editorHTML.getSession().setMode("ace/mode/html");
		    
			// this is the initialization of the CSS editor 
			var editorCSS = ace.edit("editorCSS");
			editorCSS.setTheme("ace/theme/terminal");
			editorCSS.getSession().setMode("ace/mode/css");
			editorCSS.$blockScrolling = Infinity;
		
			// this method is called when either button is clicked
			// we place the value of what's inside the editor into the global
			// window variable to relay it back to angularjs
			function getData(){
				 window.html = editorHTML.getValue();
				 window.css  = editorCSS.getValue();
			}
		
		</script>
	{% endblock %}
