<!DOCTYPE html>
<html>
	<head>
	        <meta http-equiv="Content-Type" content="text/html; charset="UTF-8">
	        <meta name="viewport" content="width=device-width">
	        
	        <!--  JS dependencies  -->
	        <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.1.9/ace.js" type="text/javascript" charset="utf-8"></script>
	     	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
			<script data-require="angular-animate@*" data-semver="1.2.0-rc2" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.0-rc.2/angular-animate.js"></script>

			<!--  CSS dependencies -->
			<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">
	     	{% block css %}{% endblock %}
	</head>
	
	<body ng-app="liveEditorApp">
			{% block content %}{% endblock %}
	</body>
	{% block javascript %}{% endblock %}
</html>